// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request structs
type CreateContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	User          *int32                 `protobuf:"varint,3,opt,name=user,proto3,oneof" json:"user,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	Pty           bool                   `protobuf:"varint,6,opt,name=pty,proto3" json:"pty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContainerRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateContainerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateContainerRequest) GetUser() int32 {
	if x != nil && x.User != nil {
		return *x.User
	}
	return 0
}

func (x *CreateContainerRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateContainerRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CreateContainerRequest) GetPty() bool {
	if x != nil {
		return x.Pty
	}
	return false
}

type ContainerIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerIdRequest) Reset() {
	*x = ContainerIdRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIdRequest) ProtoMessage() {}

func (x *ContainerIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIdRequest.ProtoReflect.Descriptor instead.
func (*ContainerIdRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContainerStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ContainerId:
	//
	//	*ContainerStatusRequest_Name
	//	*ContainerStatusRequest_Id
	ContainerId   isContainerStatusRequest_ContainerId `protobuf_oneof:"container_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatusRequest) Reset() {
	*x = ContainerStatusRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatusRequest) ProtoMessage() {}

func (x *ContainerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatusRequest.ProtoReflect.Descriptor instead.
func (*ContainerStatusRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerStatusRequest) GetContainerId() isContainerStatusRequest_ContainerId {
	if x != nil {
		return x.ContainerId
	}
	return nil
}

func (x *ContainerStatusRequest) GetName() string {
	if x != nil {
		if x, ok := x.ContainerId.(*ContainerStatusRequest_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *ContainerStatusRequest) GetId() string {
	if x != nil {
		if x, ok := x.ContainerId.(*ContainerStatusRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

type isContainerStatusRequest_ContainerId interface {
	isContainerStatusRequest_ContainerId()
}

type ContainerStatusRequest_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type ContainerStatusRequest_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

func (*ContainerStatusRequest_Name) isContainerStatusRequest_ContainerId() {}

func (*ContainerStatusRequest_Id) isContainerStatusRequest_ContainerId() {}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExecRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// Reply structs
type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

type CreateContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateContainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Nprocs        int32                  `protobuf:"varint,4,opt,name=nprocs,proto3" json:"nprocs,omitempty"`
	Procs         []int32                `protobuf:"varint,5,rep,packed,name=procs,proto3" json:"procs,omitempty"`
	Rooted        bool                   `protobuf:"varint,6,opt,name=rooted,proto3" json:"rooted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetNprocs() int32 {
	if x != nil {
		return x.Nprocs
	}
	return 0
}

func (x *Container) GetProcs() []int32 {
	if x != nil {
		return x.Procs
	}
	return nil
}

func (x *Container) GetRooted() bool {
	if x != nil {
		return x.Rooted
	}
	return false
}

type ListContainersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Conts         []*ContainerStatusResponse `protobuf:"bytes,1,rep,name=conts,proto3" json:"conts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListContainersResponse) GetConts() []*ContainerStatusResponse {
	if x != nil {
		return x.Conts
	}
	return nil
}

type ContainerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Cont          *Container             `protobuf:"bytes,2,opt,name=cont,proto3" json:"cont,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatusResponse) Reset() {
	*x = ContainerStatusResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatusResponse) ProtoMessage() {}

func (x *ContainerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatusResponse.ProtoReflect.Descriptor instead.
func (*ContainerStatusResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerStatusResponse) GetCont() *Container {
	if x != nil {
		return x.Cont
	}
	return nil
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *ExecResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AttachContainerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AttachContainerMessage_StdinData
	//	*AttachContainerMessage_StdoutData
	//	*AttachContainerMessage_ContainerId
	Payload       isAttachContainerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachContainerMessage) Reset() {
	*x = AttachContainerMessage{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachContainerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachContainerMessage) ProtoMessage() {}

func (x *AttachContainerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachContainerMessage.ProtoReflect.Descriptor instead.
func (*AttachContainerMessage) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *AttachContainerMessage) GetPayload() isAttachContainerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AttachContainerMessage) GetStdinData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AttachContainerMessage_StdinData); ok {
			return x.StdinData
		}
	}
	return nil
}

func (x *AttachContainerMessage) GetStdoutData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AttachContainerMessage_StdoutData); ok {
			return x.StdoutData
		}
	}
	return nil
}

func (x *AttachContainerMessage) GetContainerId() string {
	if x != nil {
		if x, ok := x.Payload.(*AttachContainerMessage_ContainerId); ok {
			return x.ContainerId
		}
	}
	return ""
}

type isAttachContainerMessage_Payload interface {
	isAttachContainerMessage_Payload()
}

type AttachContainerMessage_StdinData struct {
	StdinData []byte `protobuf:"bytes,1,opt,name=stdin_data,json=stdinData,proto3,oneof"`
}

type AttachContainerMessage_StdoutData struct {
	StdoutData []byte `protobuf:"bytes,2,opt,name=stdout_data,json=stdoutData,proto3,oneof"`
}

type AttachContainerMessage_ContainerId struct {
	ContainerId string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3,oneof"`
}

func (*AttachContainerMessage_StdinData) isAttachContainerMessage_Payload() {}

func (*AttachContainerMessage_StdoutData) isAttachContainerMessage_Payload() {}

func (*AttachContainerMessage_ContainerId) isAttachContainerMessage_Payload() {}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tdockerman\"\xb2\x01\n" +
	"\x16CreateContainerRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x17\n" +
	"\x04user\x18\x03 \x01(\x05H\x01R\x04user\x88\x01\x01\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12\x10\n" +
	"\x03pty\x18\x06 \x01(\bR\x03ptyB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_user\"$\n" +
	"\x12ContainerIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x16ContainerStatusRequest\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x12\x10\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02idB\x0e\n" +
	"\fcontainer_id\"O\n" +
	"\vExecRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\"\x0e\n" +
	"\fEmptyMessage\")\n" +
	"\x17CreateContainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8b\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06nprocs\x18\x04 \x01(\x05R\x06nprocs\x12\x14\n" +
	"\x05procs\x18\x05 \x03(\x05R\x05procs\x12\x16\n" +
	"\x06rooted\x18\x06 \x01(\bR\x06rooted\"R\n" +
	"\x16ListContainersResponse\x128\n" +
	"\x05conts\x18\x01 \x03(\v2\".dockerman.ContainerStatusResponseR\x05conts\"Y\n" +
	"\x17ContainerStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12(\n" +
	"\x04cont\x18\x02 \x01(\v2\x14.dockerman.ContainerR\x04cont\" \n" +
	"\fExecResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8c\x01\n" +
	"\x16AttachContainerMessage\x12\x1f\n" +
	"\n" +
	"stdin_data\x18\x01 \x01(\fH\x00R\tstdinData\x12!\n" +
	"\vstdout_data\x18\x02 \x01(\fH\x00R\n" +
	"stdoutData\x12#\n" +
	"\fcontainer_id\x18\x03 \x01(\tH\x00R\vcontainerIdB\t\n" +
	"\apayload2\x98\x05\n" +
	"\x10ContainerService\x12Z\n" +
	"\x0fCreateContainer\x12!.dockerman.CreateContainerRequest\x1a\".dockerman.CreateContainerResponse\"\x00\x12]\n" +
	"\x0fAttachContainer\x12!.dockerman.AttachContainerMessage\x1a!.dockerman.AttachContainerMessage\"\x00(\x010\x01\x12J\n" +
	"\x0eStartContainer\x12\x1d.dockerman.ContainerIdRequest\x1a\x17.dockerman.EmptyMessage\"\x00\x12I\n" +
	"\rStopContainer\x12\x1d.dockerman.ContainerIdRequest\x1a\x17.dockerman.EmptyMessage\"\x00\x12K\n" +
	"\x0fRemoveContainer\x12\x1d.dockerman.ContainerIdRequest\x1a\x17.dockerman.EmptyMessage\"\x00\x12N\n" +
	"\x0eListContainers\x12\x17.dockerman.EmptyMessage\x1a!.dockerman.ListContainersResponse\"\x00\x12Z\n" +
	"\x0fContainerStatus\x12!.dockerman.ContainerStatusRequest\x1a\".dockerman.ContainerStatusResponse\"\x00\x129\n" +
	"\x04Exec\x12\x16.dockerman.ExecRequest\x1a\x17.dockerman.ExecResponse\"\x00B\x0eZ\fdock/serviceb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_service_proto_goTypes = []any{
	(*CreateContainerRequest)(nil),  // 0: dockerman.CreateContainerRequest
	(*ContainerIdRequest)(nil),      // 1: dockerman.ContainerIdRequest
	(*ContainerStatusRequest)(nil),  // 2: dockerman.ContainerStatusRequest
	(*ExecRequest)(nil),             // 3: dockerman.ExecRequest
	(*EmptyMessage)(nil),            // 4: dockerman.EmptyMessage
	(*CreateContainerResponse)(nil), // 5: dockerman.CreateContainerResponse
	(*Container)(nil),               // 6: dockerman.Container
	(*ListContainersResponse)(nil),  // 7: dockerman.ListContainersResponse
	(*ContainerStatusResponse)(nil), // 8: dockerman.ContainerStatusResponse
	(*ExecResponse)(nil),            // 9: dockerman.ExecResponse
	(*AttachContainerMessage)(nil),  // 10: dockerman.AttachContainerMessage
}
var file_service_proto_depIdxs = []int32{
	8,  // 0: dockerman.ListContainersResponse.conts:type_name -> dockerman.ContainerStatusResponse
	6,  // 1: dockerman.ContainerStatusResponse.cont:type_name -> dockerman.Container
	0,  // 2: dockerman.ContainerService.CreateContainer:input_type -> dockerman.CreateContainerRequest
	10, // 3: dockerman.ContainerService.AttachContainer:input_type -> dockerman.AttachContainerMessage
	1,  // 4: dockerman.ContainerService.StartContainer:input_type -> dockerman.ContainerIdRequest
	1,  // 5: dockerman.ContainerService.StopContainer:input_type -> dockerman.ContainerIdRequest
	1,  // 6: dockerman.ContainerService.RemoveContainer:input_type -> dockerman.ContainerIdRequest
	4,  // 7: dockerman.ContainerService.ListContainers:input_type -> dockerman.EmptyMessage
	2,  // 8: dockerman.ContainerService.ContainerStatus:input_type -> dockerman.ContainerStatusRequest
	3,  // 9: dockerman.ContainerService.Exec:input_type -> dockerman.ExecRequest
	5,  // 10: dockerman.ContainerService.CreateContainer:output_type -> dockerman.CreateContainerResponse
	10, // 11: dockerman.ContainerService.AttachContainer:output_type -> dockerman.AttachContainerMessage
	4,  // 12: dockerman.ContainerService.StartContainer:output_type -> dockerman.EmptyMessage
	4,  // 13: dockerman.ContainerService.StopContainer:output_type -> dockerman.EmptyMessage
	4,  // 14: dockerman.ContainerService.RemoveContainer:output_type -> dockerman.EmptyMessage
	7,  // 15: dockerman.ContainerService.ListContainers:output_type -> dockerman.ListContainersResponse
	8,  // 16: dockerman.ContainerService.ContainerStatus:output_type -> dockerman.ContainerStatusResponse
	9,  // 17: dockerman.ContainerService.Exec:output_type -> dockerman.ExecResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_service_proto_msgTypes[2].OneofWrappers = []any{
		(*ContainerStatusRequest_Name)(nil),
		(*ContainerStatusRequest_Id)(nil),
	}
	file_service_proto_msgTypes[10].OneofWrappers = []any{
		(*AttachContainerMessage_StdinData)(nil),
		(*AttachContainerMessage_StdoutData)(nil),
		(*AttachContainerMessage_ContainerId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
