// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerState int32

const (
	ContainerState_RUNNING ContainerState = 0
	ContainerState_STOPPED ContainerState = 1
	ContainerState_FROZEN  ContainerState = 2
)

// Enum value maps for ContainerState.
var (
	ContainerState_name = map[int32]string{
		0: "RUNNING",
		1: "STOPPED",
		2: "FROZEN",
	}
	ContainerState_value = map[string]int32{
		"RUNNING": 0,
		"STOPPED": 1,
		"FROZEN":  2,
	}
)

func (x ContainerState) Enum() *ContainerState {
	p := new(ContainerState)
	*p = x
	return p
}

func (x ContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (ContainerState) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x ContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState.Descriptor instead.
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// Request structs
type CreateContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	User          *int32                 `protobuf:"varint,3,opt,name=user,proto3,oneof" json:"user,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	Pty           bool                   `protobuf:"varint,6,opt,name=pty,proto3" json:"pty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContainerRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateContainerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateContainerRequest) GetUser() int32 {
	if x != nil && x.User != nil {
		return *x.User
	}
	return 0
}

func (x *CreateContainerRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateContainerRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CreateContainerRequest) GetPty() bool {
	if x != nil {
		return x.Pty
	}
	return false
}

type ContainerIdNameRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContainerIdName string                 `protobuf:"bytes,1,opt,name=container_id_name,json=containerIdName,proto3" json:"container_id_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContainerIdNameRequest) Reset() {
	*x = ContainerIdNameRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerIdNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIdNameRequest) ProtoMessage() {}

func (x *ContainerIdNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIdNameRequest.ProtoReflect.Descriptor instead.
func (*ContainerIdNameRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerIdNameRequest) GetContainerIdName() string {
	if x != nil {
		return x.ContainerIdName
	}
	return ""
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// Reply structs
type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

type CreateContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateContainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Procs         []int32                `protobuf:"varint,5,rep,packed,name=procs,proto3" json:"procs,omitempty"`
	Rooted        bool                   `protobuf:"varint,6,opt,name=rooted,proto3" json:"rooted,omitempty"`
	Cmd           string                 `protobuf:"bytes,7,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          []string               `protobuf:"bytes,8,rep,name=args,proto3" json:"args,omitempty"`
	State         ContainerState         `protobuf:"varint,9,opt,name=state,proto3,enum=dockerman.ContainerState" json:"state,omitempty"`
	Pty           bool                   `protobuf:"varint,10,opt,name=Pty,proto3" json:"Pty,omitempty"`
	User          int32                  `protobuf:"varint,11,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetProcs() []int32 {
	if x != nil {
		return x.Procs
	}
	return nil
}

func (x *Container) GetRooted() bool {
	if x != nil {
		return x.Rooted
	}
	return false
}

func (x *Container) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Container) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Container) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_RUNNING
}

func (x *Container) GetPty() bool {
	if x != nil {
		return x.Pty
	}
	return false
}

func (x *Container) GetUser() int32 {
	if x != nil {
		return x.User
	}
	return 0
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conts         []*Container           `protobuf:"bytes,1,rep,name=conts,proto3" json:"conts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListContainersResponse) GetConts() []*Container {
	if x != nil {
		return x.Conts
	}
	return nil
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *ExecResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AttachContainerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AttachContainerMessage_StdinData
	//	*AttachContainerMessage_StdoutData
	//	*AttachContainerMessage_ContainerId
	Payload       isAttachContainerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachContainerMessage) Reset() {
	*x = AttachContainerMessage{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachContainerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachContainerMessage) ProtoMessage() {}

func (x *AttachContainerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachContainerMessage.ProtoReflect.Descriptor instead.
func (*AttachContainerMessage) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *AttachContainerMessage) GetPayload() isAttachContainerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AttachContainerMessage) GetStdinData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AttachContainerMessage_StdinData); ok {
			return x.StdinData
		}
	}
	return nil
}

func (x *AttachContainerMessage) GetStdoutData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*AttachContainerMessage_StdoutData); ok {
			return x.StdoutData
		}
	}
	return nil
}

func (x *AttachContainerMessage) GetContainerId() string {
	if x != nil {
		if x, ok := x.Payload.(*AttachContainerMessage_ContainerId); ok {
			return x.ContainerId
		}
	}
	return ""
}

type isAttachContainerMessage_Payload interface {
	isAttachContainerMessage_Payload()
}

type AttachContainerMessage_StdinData struct {
	StdinData []byte `protobuf:"bytes,1,opt,name=stdin_data,json=stdinData,proto3,oneof"`
}

type AttachContainerMessage_StdoutData struct {
	StdoutData []byte `protobuf:"bytes,2,opt,name=stdout_data,json=stdoutData,proto3,oneof"`
}

type AttachContainerMessage_ContainerId struct {
	ContainerId string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3,oneof"`
}

func (*AttachContainerMessage_StdinData) isAttachContainerMessage_Payload() {}

func (*AttachContainerMessage_StdoutData) isAttachContainerMessage_Payload() {}

func (*AttachContainerMessage_ContainerId) isAttachContainerMessage_Payload() {}

type ExecContainerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecContainerMessage_StdinData
	//	*ExecContainerMessage_StdoutData
	//	*ExecContainerMessage_Proc
	Payload       isExecContainerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecContainerMessage) Reset() {
	*x = ExecContainerMessage{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecContainerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecContainerMessage) ProtoMessage() {}

func (x *ExecContainerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecContainerMessage.ProtoReflect.Descriptor instead.
func (*ExecContainerMessage) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *ExecContainerMessage) GetPayload() isExecContainerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecContainerMessage) GetStdinData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerMessage_StdinData); ok {
			return x.StdinData
		}
	}
	return nil
}

func (x *ExecContainerMessage) GetStdoutData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerMessage_StdoutData); ok {
			return x.StdoutData
		}
	}
	return nil
}

func (x *ExecContainerMessage) GetProc() *ExecProcess {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerMessage_Proc); ok {
			return x.Proc
		}
	}
	return nil
}

type isExecContainerMessage_Payload interface {
	isExecContainerMessage_Payload()
}

type ExecContainerMessage_StdinData struct {
	StdinData []byte `protobuf:"bytes,1,opt,name=stdin_data,json=stdinData,proto3,oneof"`
}

type ExecContainerMessage_StdoutData struct {
	StdoutData []byte `protobuf:"bytes,2,opt,name=stdout_data,json=stdoutData,proto3,oneof"`
}

type ExecContainerMessage_Proc struct {
	Proc *ExecProcess `protobuf:"bytes,3,opt,name=proc,proto3,oneof"`
}

func (*ExecContainerMessage_StdinData) isExecContainerMessage_Payload() {}

func (*ExecContainerMessage_StdoutData) isExecContainerMessage_Payload() {}

func (*ExecContainerMessage_Proc) isExecContainerMessage_Payload() {}

type ExecProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Cmdline       []string               `protobuf:"bytes,2,rep,name=cmdline,proto3" json:"cmdline,omitempty"`
	Interactive   bool                   `protobuf:"varint,3,opt,name=interactive,proto3" json:"interactive,omitempty"`
	Pty           bool                   `protobuf:"varint,4,opt,name=pty,proto3" json:"pty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecProcess) Reset() {
	*x = ExecProcess{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecProcess) ProtoMessage() {}

func (x *ExecProcess) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecProcess.ProtoReflect.Descriptor instead.
func (*ExecProcess) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *ExecProcess) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ExecProcess) GetCmdline() []string {
	if x != nil {
		return x.Cmdline
	}
	return nil
}

func (x *ExecProcess) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *ExecProcess) GetPty() bool {
	if x != nil {
		return x.Pty
	}
	return false
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tdockerman\"\xb2\x01\n" +
	"\x16CreateContainerRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x17\n" +
	"\x04user\x18\x03 \x01(\x05H\x01R\x04user\x88\x01\x01\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12\x10\n" +
	"\x03pty\x18\x06 \x01(\bR\x03ptyB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_user\"D\n" +
	"\x16ContainerIdNameRequest\x12*\n" +
	"\x11container_id_name\x18\x01 \x01(\tR\x0fcontainerIdName\"O\n" +
	"\vExecRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\"\x0e\n" +
	"\fEmptyMessage\")\n" +
	"\x17CreateContainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf0\x01\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05procs\x18\x05 \x03(\x05R\x05procs\x12\x16\n" +
	"\x06rooted\x18\x06 \x01(\bR\x06rooted\x12\x10\n" +
	"\x03cmd\x18\a \x01(\tR\x03cmd\x12\x12\n" +
	"\x04args\x18\b \x03(\tR\x04args\x12/\n" +
	"\x05state\x18\t \x01(\x0e2\x19.dockerman.ContainerStateR\x05state\x12\x10\n" +
	"\x03Pty\x18\n" +
	" \x01(\bR\x03Pty\x12\x12\n" +
	"\x04user\x18\v \x01(\x05R\x04user\"D\n" +
	"\x16ListContainersResponse\x12*\n" +
	"\x05conts\x18\x01 \x03(\v2\x14.dockerman.ContainerR\x05conts\" \n" +
	"\fExecResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8c\x01\n" +
	"\x16AttachContainerMessage\x12\x1f\n" +
	"\n" +
	"stdin_data\x18\x01 \x01(\fH\x00R\tstdinData\x12!\n" +
	"\vstdout_data\x18\x02 \x01(\fH\x00R\n" +
	"stdoutData\x12#\n" +
	"\fcontainer_id\x18\x03 \x01(\tH\x00R\vcontainerIdB\t\n" +
	"\apayload\"\x93\x01\n" +
	"\x14ExecContainerMessage\x12\x1f\n" +
	"\n" +
	"stdin_data\x18\x01 \x01(\fH\x00R\tstdinData\x12!\n" +
	"\vstdout_data\x18\x02 \x01(\fH\x00R\n" +
	"stdoutData\x12,\n" +
	"\x04proc\x18\x03 \x01(\v2\x16.dockerman.ExecProcessH\x00R\x04procB\t\n" +
	"\apayload\"~\n" +
	"\vExecProcess\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\acmdline\x18\x02 \x03(\tR\acmdline\x12 \n" +
	"\vinteractive\x18\x03 \x01(\bR\vinteractive\x12\x10\n" +
	"\x03pty\x18\x04 \x01(\bR\x03pty*6\n" +
	"\x0eContainerState\x12\v\n" +
	"\aRUNNING\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\n" +
	"\n" +
	"\x06FROZEN\x10\x022\xcf\x06\n" +
	"\x10ContainerService\x12Z\n" +
	"\x0fCreateContainer\x12!.dockerman.CreateContainerRequest\x1a\".dockerman.CreateContainerResponse\"\x00\x12]\n" +
	"\x0fAttachContainer\x12!.dockerman.AttachContainerMessage\x1a!.dockerman.AttachContainerMessage\"\x00(\x010\x01\x12N\n" +
	"\x0eStartContainer\x12!.dockerman.ContainerIdNameRequest\x1a\x17.dockerman.EmptyMessage\"\x00\x12M\n" +
	"\rStopContainer\x12!.dockerman.ContainerIdNameRequest\x1a\x17.dockerman.EmptyMessage\"\x00\x12O\n" +
	"\x0fRemoveContainer\x12!.dockerman.ContainerIdNameRequest\x1a\x17.dockerman.EmptyMessage\"\x00\x12O\n" +
	"\x0fFreezeContainer\x12!.dockerman.ContainerIdNameRequest\x1a\x17.dockerman.EmptyMessage\"\x00\x12Q\n" +
	"\x11UnfreezeContainer\x12!.dockerman.ContainerIdNameRequest\x1a\x17.dockerman.EmptyMessage\"\x00\x12N\n" +
	"\x0eListContainers\x12\x17.dockerman.EmptyMessage\x1a!.dockerman.ListContainersResponse\"\x00\x12L\n" +
	"\x0fContainerStatus\x12!.dockerman.ContainerIdNameRequest\x1a\x14.dockerman.Container\"\x00\x12N\n" +
	"\x04Exec\x12\x1f.dockerman.ExecContainerMessage\x1a\x1f.dockerman.ExecContainerMessage\"\x00(\x010\x01B\x0eZ\fdock/serviceb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_service_proto_goTypes = []any{
	(ContainerState)(0),             // 0: dockerman.ContainerState
	(*CreateContainerRequest)(nil),  // 1: dockerman.CreateContainerRequest
	(*ContainerIdNameRequest)(nil),  // 2: dockerman.ContainerIdNameRequest
	(*ExecRequest)(nil),             // 3: dockerman.ExecRequest
	(*EmptyMessage)(nil),            // 4: dockerman.EmptyMessage
	(*CreateContainerResponse)(nil), // 5: dockerman.CreateContainerResponse
	(*Container)(nil),               // 6: dockerman.Container
	(*ListContainersResponse)(nil),  // 7: dockerman.ListContainersResponse
	(*ExecResponse)(nil),            // 8: dockerman.ExecResponse
	(*AttachContainerMessage)(nil),  // 9: dockerman.AttachContainerMessage
	(*ExecContainerMessage)(nil),    // 10: dockerman.ExecContainerMessage
	(*ExecProcess)(nil),             // 11: dockerman.ExecProcess
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: dockerman.Container.state:type_name -> dockerman.ContainerState
	6,  // 1: dockerman.ListContainersResponse.conts:type_name -> dockerman.Container
	11, // 2: dockerman.ExecContainerMessage.proc:type_name -> dockerman.ExecProcess
	1,  // 3: dockerman.ContainerService.CreateContainer:input_type -> dockerman.CreateContainerRequest
	9,  // 4: dockerman.ContainerService.AttachContainer:input_type -> dockerman.AttachContainerMessage
	2,  // 5: dockerman.ContainerService.StartContainer:input_type -> dockerman.ContainerIdNameRequest
	2,  // 6: dockerman.ContainerService.StopContainer:input_type -> dockerman.ContainerIdNameRequest
	2,  // 7: dockerman.ContainerService.RemoveContainer:input_type -> dockerman.ContainerIdNameRequest
	2,  // 8: dockerman.ContainerService.FreezeContainer:input_type -> dockerman.ContainerIdNameRequest
	2,  // 9: dockerman.ContainerService.UnfreezeContainer:input_type -> dockerman.ContainerIdNameRequest
	4,  // 10: dockerman.ContainerService.ListContainers:input_type -> dockerman.EmptyMessage
	2,  // 11: dockerman.ContainerService.ContainerStatus:input_type -> dockerman.ContainerIdNameRequest
	10, // 12: dockerman.ContainerService.Exec:input_type -> dockerman.ExecContainerMessage
	5,  // 13: dockerman.ContainerService.CreateContainer:output_type -> dockerman.CreateContainerResponse
	9,  // 14: dockerman.ContainerService.AttachContainer:output_type -> dockerman.AttachContainerMessage
	4,  // 15: dockerman.ContainerService.StartContainer:output_type -> dockerman.EmptyMessage
	4,  // 16: dockerman.ContainerService.StopContainer:output_type -> dockerman.EmptyMessage
	4,  // 17: dockerman.ContainerService.RemoveContainer:output_type -> dockerman.EmptyMessage
	4,  // 18: dockerman.ContainerService.FreezeContainer:output_type -> dockerman.EmptyMessage
	4,  // 19: dockerman.ContainerService.UnfreezeContainer:output_type -> dockerman.EmptyMessage
	7,  // 20: dockerman.ContainerService.ListContainers:output_type -> dockerman.ListContainersResponse
	6,  // 21: dockerman.ContainerService.ContainerStatus:output_type -> dockerman.Container
	10, // 22: dockerman.ContainerService.Exec:output_type -> dockerman.ExecContainerMessage
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_service_proto_msgTypes[8].OneofWrappers = []any{
		(*AttachContainerMessage_StdinData)(nil),
		(*AttachContainerMessage_StdoutData)(nil),
		(*AttachContainerMessage_ContainerId)(nil),
	}
	file_service_proto_msgTypes[9].OneofWrappers = []any{
		(*ExecContainerMessage_StdinData)(nil),
		(*ExecContainerMessage_StdoutData)(nil),
		(*ExecContainerMessage_Proc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
